version: 2
updates:
- package-ecosystem: gomod
  directory: "/tools"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  cooldown:
    default-days: 5

- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  cooldown:
    default-days: 5

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  cooldown:
    default-days: 5
