// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"
	"regexp"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermRedisCacheInvalidPrivateStaticIPAddressRule checks the pattern is valid
type AzurermRedisCacheInvalidPrivateStaticIPAddressRule struct {
	resourceType  string
	attributeName string
	pattern       *regexp.Regexp
}

// NewAzurermRedisCacheInvalidPrivateStaticIPAddressRule returns new rule with default attributes
func NewAzurermRedisCacheInvalidPrivateStaticIPAddressRule() *AzurermRedisCacheInvalidPrivateStaticIPAddressRule {
	return &AzurermRedisCacheInvalidPrivateStaticIPAddressRule{
		resourceType:  "azurerm_redis_cache",
		attributeName: "private_static_ip_address",
		pattern:       regexp.MustCompile(`^\d+\.\d+\.\d+\.\d+$`),
	}
}

// Name returns the rule name
func (r *AzurermRedisCacheInvalidPrivateStaticIPAddressRule) Name() string {
	return "azurerm_redis_cache_invalid_private_static_ip_address"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermRedisCacheInvalidPrivateStaticIPAddressRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermRedisCacheInvalidPrivateStaticIPAddressRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermRedisCacheInvalidPrivateStaticIPAddressRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermRedisCacheInvalidPrivateStaticIPAddressRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if !r.pattern.MatchString(val) {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^\d+\.\d+\.\d+\.\d+$`),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
