// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermDataLakeStoreInvalidFirewallAllowAzureIpsRule checks the pattern is valid
type AzurermDataLakeStoreInvalidFirewallAllowAzureIpsRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermDataLakeStoreInvalidFirewallAllowAzureIpsRule returns new rule with default attributes
func NewAzurermDataLakeStoreInvalidFirewallAllowAzureIpsRule() *AzurermDataLakeStoreInvalidFirewallAllowAzureIpsRule {
	return &AzurermDataLakeStoreInvalidFirewallAllowAzureIpsRule{
		resourceType:  "azurerm_data_lake_store",
		attributeName: "firewall_allow_azure_ips",
		enum: []string{
			"Enabled",
			"Disabled",
		},
	}
}

// Name returns the rule name
func (r *AzurermDataLakeStoreInvalidFirewallAllowAzureIpsRule) Name() string {
	return "azurerm_data_lake_store_invalid_firewall_allow_azure_ips"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermDataLakeStoreInvalidFirewallAllowAzureIpsRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermDataLakeStoreInvalidFirewallAllowAzureIpsRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermDataLakeStoreInvalidFirewallAllowAzureIpsRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermDataLakeStoreInvalidFirewallAllowAzureIpsRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as firewall_allow_azure_ips`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
