// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"
	"regexp"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AzurermBatchPoolInvalidNameRule checks the pattern is valid
type AzurermBatchPoolInvalidNameRule struct {
	resourceType  string
	attributeName string
	pattern       *regexp.Regexp
}

// NewAzurermBatchPoolInvalidNameRule returns new rule with default attributes
func NewAzurermBatchPoolInvalidNameRule() *AzurermBatchPoolInvalidNameRule {
	return &AzurermBatchPoolInvalidNameRule{
		resourceType:  "azurerm_batch_pool",
		attributeName: "name",
		pattern:       regexp.MustCompile(`^[a-zA-Z0-9_-]+$`),
	}
}

// Name returns the rule name
func (r *AzurermBatchPoolInvalidNameRule) Name() string {
	return "azurerm_batch_pool_invalid_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermBatchPoolInvalidNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermBatchPoolInvalidNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermBatchPoolInvalidNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AzurermBatchPoolInvalidNameRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if !r.pattern.MatchString(val) {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^[a-zA-Z0-9_-]+$`),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
