// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermMariadbServerInvalidSslEnforcementRule checks the pattern is valid
type AzurermMariadbServerInvalidSslEnforcementRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermMariadbServerInvalidSslEnforcementRule returns new rule with default attributes
func NewAzurermMariadbServerInvalidSslEnforcementRule() *AzurermMariadbServerInvalidSslEnforcementRule {
	return &AzurermMariadbServerInvalidSslEnforcementRule{
		resourceType:  "azurerm_mariadb_server",
		attributeName: "ssl_enforcement",
		enum: []string{
			"Enabled",
			"Disabled",
		},
	}
}

// Name returns the rule name
func (r *AzurermMariadbServerInvalidSslEnforcementRule) Name() string {
	return "azurerm_mariadb_server_invalid_ssl_enforcement"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermMariadbServerInvalidSslEnforcementRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermMariadbServerInvalidSslEnforcementRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermMariadbServerInvalidSslEnforcementRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermMariadbServerInvalidSslEnforcementRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" is an invalid value as ssl_enforcement`, truncateLongMessage(val)),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
