// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AzurermFirewallNatRuleCollectionInvalidActionRule checks the pattern is valid
type AzurermFirewallNatRuleCollectionInvalidActionRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermFirewallNatRuleCollectionInvalidActionRule returns new rule with default attributes
func NewAzurermFirewallNatRuleCollectionInvalidActionRule() *AzurermFirewallNatRuleCollectionInvalidActionRule {
	return &AzurermFirewallNatRuleCollectionInvalidActionRule{
		resourceType:  "azurerm_firewall_nat_rule_collection",
		attributeName: "action",
		enum: []string{
			"Snat",
			"Dnat",
		},
	}
}

// Name returns the rule name
func (r *AzurermFirewallNatRuleCollectionInvalidActionRule) Name() string {
	return "azurerm_firewall_nat_rule_collection_invalid_action"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermFirewallNatRuleCollectionInvalidActionRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermFirewallNatRuleCollectionInvalidActionRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermFirewallNatRuleCollectionInvalidActionRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AzurermFirewallNatRuleCollectionInvalidActionRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as action`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
