// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AzurermAutomationAccountInvalidSkuNameRule checks the pattern is valid
type AzurermAutomationAccountInvalidSkuNameRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermAutomationAccountInvalidSkuNameRule returns new rule with default attributes
func NewAzurermAutomationAccountInvalidSkuNameRule() *AzurermAutomationAccountInvalidSkuNameRule {
	return &AzurermAutomationAccountInvalidSkuNameRule{
		resourceType:  "azurerm_automation_account",
		attributeName: "sku_name",
		enum: []string{
			"Free",
			"Basic",
		},
	}
}

// Name returns the rule name
func (r *AzurermAutomationAccountInvalidSkuNameRule) Name() string {
	return "azurerm_automation_account_invalid_sku_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermAutomationAccountInvalidSkuNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermAutomationAccountInvalidSkuNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermAutomationAccountInvalidSkuNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AzurermAutomationAccountInvalidSkuNameRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as sku_name`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
