// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule checks the pattern is valid
type AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
}

// NewAzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule returns new rule with default attributes
func NewAzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule() *AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule {
	return &AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule{
		resourceType:  "azurerm_kubernetes_cluster_node_pool",
		attributeName: "os_disk_size_gb",
		max:           1023,
		min:           0,
	}
}

// Name returns the rule name
func (r *AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule) Name() string {
	return "azurerm_kubernetes_cluster_node_pool_invalid_os_disk_size_gb"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val int
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if val > r.max {
				runner.EmitIssueOnExpr(
					r,
					"os_disk_size_gb must be 1023 or less",
					attribute.Expr,
				)
			}
			if val < r.min {
				runner.EmitIssueOnExpr(
					r,
					"os_disk_size_gb must be 0 or higher",
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
