// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermLbRuleInvalidProtocolRule checks the pattern is valid
type AzurermLbRuleInvalidProtocolRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermLbRuleInvalidProtocolRule returns new rule with default attributes
func NewAzurermLbRuleInvalidProtocolRule() *AzurermLbRuleInvalidProtocolRule {
	return &AzurermLbRuleInvalidProtocolRule{
		resourceType:  "azurerm_lb_rule",
		attributeName: "protocol",
		enum: []string{
			"Udp",
			"Tcp",
			"All",
		},
	}
}

// Name returns the rule name
func (r *AzurermLbRuleInvalidProtocolRule) Name() string {
	return "azurerm_lb_rule_invalid_protocol"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermLbRuleInvalidProtocolRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermLbRuleInvalidProtocolRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermLbRuleInvalidProtocolRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermLbRuleInvalidProtocolRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}
		err := runner.EvaluateExpr(attribute.Expr, func (val string) error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as protocol`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
