// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AzurermSharedImageInvalidOSTypeRule checks the pattern is valid
type AzurermSharedImageInvalidOSTypeRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermSharedImageInvalidOSTypeRule returns new rule with default attributes
func NewAzurermSharedImageInvalidOSTypeRule() *AzurermSharedImageInvalidOSTypeRule {
	return &AzurermSharedImageInvalidOSTypeRule{
		resourceType:  "azurerm_shared_image",
		attributeName: "os_type",
		enum: []string{
			"Windows",
			"Linux",
		},
	}
}

// Name returns the rule name
func (r *AzurermSharedImageInvalidOSTypeRule) Name() string {
	return "azurerm_shared_image_invalid_os_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermSharedImageInvalidOSTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermSharedImageInvalidOSTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermSharedImageInvalidOSTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AzurermSharedImageInvalidOSTypeRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as os_type`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
