// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermEventgridEventSubscriptionInvalidEventDeliverySchemaRule checks the pattern is valid
type AzurermEventgridEventSubscriptionInvalidEventDeliverySchemaRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermEventgridEventSubscriptionInvalidEventDeliverySchemaRule returns new rule with default attributes
func NewAzurermEventgridEventSubscriptionInvalidEventDeliverySchemaRule() *AzurermEventgridEventSubscriptionInvalidEventDeliverySchemaRule {
	return &AzurermEventgridEventSubscriptionInvalidEventDeliverySchemaRule{
		resourceType:  "azurerm_eventgrid_event_subscription",
		attributeName: "event_delivery_schema",
		enum: []string{
			"EventGridSchema",
			"CustomInputSchema",
			"CloudEventSchemaV1_0",
		},
	}
}

// Name returns the rule name
func (r *AzurermEventgridEventSubscriptionInvalidEventDeliverySchemaRule) Name() string {
	return "azurerm_eventgrid_event_subscription_invalid_event_delivery_schema"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermEventgridEventSubscriptionInvalidEventDeliverySchemaRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermEventgridEventSubscriptionInvalidEventDeliverySchemaRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermEventgridEventSubscriptionInvalidEventDeliverySchemaRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermEventgridEventSubscriptionInvalidEventDeliverySchemaRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" is an invalid value as event_delivery_schema`, truncateLongMessage(val)),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
