// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermSQLDatabaseInvalidCreateModeRule checks the pattern is valid
type AzurermSQLDatabaseInvalidCreateModeRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermSQLDatabaseInvalidCreateModeRule returns new rule with default attributes
func NewAzurermSQLDatabaseInvalidCreateModeRule() *AzurermSQLDatabaseInvalidCreateModeRule {
	return &AzurermSQLDatabaseInvalidCreateModeRule{
		resourceType:  "azurerm_sql_database",
		attributeName: "create_mode",
		enum: []string{
			"Default",
			"Copy",
			"Secondary",
			"OnlineSecondary",
			"PointInTimeRestore",
			"Restore",
			"Recovery",
			"RestoreExternalBackup",
			"RestoreExternalBackupSecondary",
			"RestoreLongTermRetentionBackup",
		},
	}
}

// Name returns the rule name
func (r *AzurermSQLDatabaseInvalidCreateModeRule) Name() string {
	return "azurerm_sql_database_invalid_create_mode"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermSQLDatabaseInvalidCreateModeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermSQLDatabaseInvalidCreateModeRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermSQLDatabaseInvalidCreateModeRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermSQLDatabaseInvalidCreateModeRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}
		err := runner.EvaluateExpr(attribute.Expr, func (val string) error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as create_mode`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
