// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermDataLakeStoreInvalidTierRule checks the pattern is valid
type AzurermDataLakeStoreInvalidTierRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermDataLakeStoreInvalidTierRule returns new rule with default attributes
func NewAzurermDataLakeStoreInvalidTierRule() *AzurermDataLakeStoreInvalidTierRule {
	return &AzurermDataLakeStoreInvalidTierRule{
		resourceType:  "azurerm_data_lake_store",
		attributeName: "tier",
		enum: []string{
			"Consumption",
			"Commitment_1TB",
			"Commitment_10TB",
			"Commitment_100TB",
			"Commitment_500TB",
			"Commitment_1PB",
			"Commitment_5PB",
		},
	}
}

// Name returns the rule name
func (r *AzurermDataLakeStoreInvalidTierRule) Name() string {
	return "azurerm_data_lake_store_invalid_tier"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermDataLakeStoreInvalidTierRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermDataLakeStoreInvalidTierRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermDataLakeStoreInvalidTierRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermDataLakeStoreInvalidTierRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as tier`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
