// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermApplicationInsightsAnalyticsItemInvalidScopeRule checks the pattern is valid
type AzurermApplicationInsightsAnalyticsItemInvalidScopeRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermApplicationInsightsAnalyticsItemInvalidScopeRule returns new rule with default attributes
func NewAzurermApplicationInsightsAnalyticsItemInvalidScopeRule() *AzurermApplicationInsightsAnalyticsItemInvalidScopeRule {
	return &AzurermApplicationInsightsAnalyticsItemInvalidScopeRule{
		resourceType:  "azurerm_application_insights_analytics_item",
		attributeName: "scope",
		enum: []string{
			"shared",
			"user",
		},
	}
}

// Name returns the rule name
func (r *AzurermApplicationInsightsAnalyticsItemInvalidScopeRule) Name() string {
	return "azurerm_application_insights_analytics_item_invalid_scope"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermApplicationInsightsAnalyticsItemInvalidScopeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermApplicationInsightsAnalyticsItemInvalidScopeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermApplicationInsightsAnalyticsItemInvalidScopeRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermApplicationInsightsAnalyticsItemInvalidScopeRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as scope`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
