// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermRedisCacheInvalidSkuNameRule checks the pattern is valid
type AzurermRedisCacheInvalidSkuNameRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermRedisCacheInvalidSkuNameRule returns new rule with default attributes
func NewAzurermRedisCacheInvalidSkuNameRule() *AzurermRedisCacheInvalidSkuNameRule {
	return &AzurermRedisCacheInvalidSkuNameRule{
		resourceType:  "azurerm_redis_cache",
		attributeName: "sku_name",
		enum: []string{
			"Basic",
			"Standard",
			"Premium",
		},
	}
}

// Name returns the rule name
func (r *AzurermRedisCacheInvalidSkuNameRule) Name() string {
	return "azurerm_redis_cache_invalid_sku_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermRedisCacheInvalidSkuNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermRedisCacheInvalidSkuNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermRedisCacheInvalidSkuNameRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermRedisCacheInvalidSkuNameRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as sku_name`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
