// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"
	"regexp"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AzurermCosmosdbAccountInvalidNameRule checks the pattern is valid
type AzurermCosmosdbAccountInvalidNameRule struct {
	resourceType  string
	attributeName string
	pattern       *regexp.Regexp
}

// NewAzurermCosmosdbAccountInvalidNameRule returns new rule with default attributes
func NewAzurermCosmosdbAccountInvalidNameRule() *AzurermCosmosdbAccountInvalidNameRule {
	return &AzurermCosmosdbAccountInvalidNameRule{
		resourceType:  "azurerm_cosmosdb_account",
		attributeName: "name",
		pattern:       regexp.MustCompile(`^[a-z0-9]+(-[a-z0-9]+)*`),
	}
}

// Name returns the rule name
func (r *AzurermCosmosdbAccountInvalidNameRule) Name() string {
	return "azurerm_cosmosdb_account_invalid_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermCosmosdbAccountInvalidNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermCosmosdbAccountInvalidNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermCosmosdbAccountInvalidNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AzurermCosmosdbAccountInvalidNameRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if !r.pattern.MatchString(val) {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^[a-z0-9]+(-[a-z0-9]+)*`),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
