// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AzurermPostgresqlServerInvalidVersionRule checks the pattern is valid
type AzurermPostgresqlServerInvalidVersionRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermPostgresqlServerInvalidVersionRule returns new rule with default attributes
func NewAzurermPostgresqlServerInvalidVersionRule() *AzurermPostgresqlServerInvalidVersionRule {
	return &AzurermPostgresqlServerInvalidVersionRule{
		resourceType:  "azurerm_postgresql_server",
		attributeName: "version",
		enum: []string{
			"9.5",
			"9.6",
			"10",
			"10.0",
			"10.2",
			"11",
		},
	}
}

// Name returns the rule name
func (r *AzurermPostgresqlServerInvalidVersionRule) Name() string {
	return "azurerm_postgresql_server_invalid_version"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermPostgresqlServerInvalidVersionRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermPostgresqlServerInvalidVersionRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermPostgresqlServerInvalidVersionRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AzurermPostgresqlServerInvalidVersionRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as version`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
