// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"
	"regexp"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermHpcCacheInvalidNameRule checks the pattern is valid
type AzurermHpcCacheInvalidNameRule struct {
	resourceType  string
	attributeName string
	pattern       *regexp.Regexp
}

// NewAzurermHpcCacheInvalidNameRule returns new rule with default attributes
func NewAzurermHpcCacheInvalidNameRule() *AzurermHpcCacheInvalidNameRule {
	return &AzurermHpcCacheInvalidNameRule{
		resourceType:  "azurerm_hpc_cache",
		attributeName: "name",
		pattern:       regexp.MustCompile(`^[-0-9a-zA-Z_]{1,80}$`),
	}
}

// Name returns the rule name
func (r *AzurermHpcCacheInvalidNameRule) Name() string {
	return "azurerm_hpc_cache_invalid_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermHpcCacheInvalidNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermHpcCacheInvalidNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermHpcCacheInvalidNameRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermHpcCacheInvalidNameRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if !r.pattern.MatchString(val) {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^[-0-9a-zA-Z_]{1,80}$`),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
