// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermContainerGroupInvalidIPAddressTypeRule checks the pattern is valid
type AzurermContainerGroupInvalidIPAddressTypeRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermContainerGroupInvalidIPAddressTypeRule returns new rule with default attributes
func NewAzurermContainerGroupInvalidIPAddressTypeRule() *AzurermContainerGroupInvalidIPAddressTypeRule {
	return &AzurermContainerGroupInvalidIPAddressTypeRule{
		resourceType:  "azurerm_container_group",
		attributeName: "ip_address_type",
		enum: []string{
			"Public",
			"Private",
		},
	}
}

// Name returns the rule name
func (r *AzurermContainerGroupInvalidIPAddressTypeRule) Name() string {
	return "azurerm_container_group_invalid_ip_address_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermContainerGroupInvalidIPAddressTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermContainerGroupInvalidIPAddressTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermContainerGroupInvalidIPAddressTypeRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermContainerGroupInvalidIPAddressTypeRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as ip_address_type`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
