// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermPacketCaptureInvalidMaximumBytesPerSessionRule checks the pattern is valid
type AzurermPacketCaptureInvalidMaximumBytesPerSessionRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
}

// NewAzurermPacketCaptureInvalidMaximumBytesPerSessionRule returns new rule with default attributes
func NewAzurermPacketCaptureInvalidMaximumBytesPerSessionRule() *AzurermPacketCaptureInvalidMaximumBytesPerSessionRule {
	return &AzurermPacketCaptureInvalidMaximumBytesPerSessionRule{
		resourceType:  "azurerm_packet_capture",
		attributeName: "maximum_bytes_per_session",
		max:           4294967295,
		min:           0,
	}
}

// Name returns the rule name
func (r *AzurermPacketCaptureInvalidMaximumBytesPerSessionRule) Name() string {
	return "azurerm_packet_capture_invalid_maximum_bytes_per_session"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermPacketCaptureInvalidMaximumBytesPerSessionRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermPacketCaptureInvalidMaximumBytesPerSessionRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermPacketCaptureInvalidMaximumBytesPerSessionRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermPacketCaptureInvalidMaximumBytesPerSessionRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val int
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if val > r.max {
				runner.EmitIssueOnExpr(
					r,
					"maximum_bytes_per_session must be 4294967295 or less",
					attribute.Expr,
				)
			}
			if val < r.min {
				runner.EmitIssueOnExpr(
					r,
					"maximum_bytes_per_session must be 0 or higher",
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
