// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AzurermKeyVaultKeyInvalidCurveRule checks the pattern is valid
type AzurermKeyVaultKeyInvalidCurveRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermKeyVaultKeyInvalidCurveRule returns new rule with default attributes
func NewAzurermKeyVaultKeyInvalidCurveRule() *AzurermKeyVaultKeyInvalidCurveRule {
	return &AzurermKeyVaultKeyInvalidCurveRule{
		resourceType:  "azurerm_key_vault_key",
		attributeName: "curve",
		enum: []string{
			"P-256",
			"P-384",
			"P-521",
			"SECP256K1",
		},
	}
}

// Name returns the rule name
func (r *AzurermKeyVaultKeyInvalidCurveRule) Name() string {
	return "azurerm_key_vault_key_invalid_curve"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermKeyVaultKeyInvalidCurveRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermKeyVaultKeyInvalidCurveRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermKeyVaultKeyInvalidCurveRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AzurermKeyVaultKeyInvalidCurveRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as curve`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
