// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermKustoDatabasePrincipalInvalidTypeRule checks the pattern is valid
type AzurermKustoDatabasePrincipalInvalidTypeRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermKustoDatabasePrincipalInvalidTypeRule returns new rule with default attributes
func NewAzurermKustoDatabasePrincipalInvalidTypeRule() *AzurermKustoDatabasePrincipalInvalidTypeRule {
	return &AzurermKustoDatabasePrincipalInvalidTypeRule{
		resourceType:  "azurerm_kusto_database_principal",
		attributeName: "type",
		enum: []string{
			"App",
			"Group",
			"User",
		},
	}
}

// Name returns the rule name
func (r *AzurermKustoDatabasePrincipalInvalidTypeRule) Name() string {
	return "azurerm_kusto_database_principal_invalid_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermKustoDatabasePrincipalInvalidTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermKustoDatabasePrincipalInvalidTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermKustoDatabasePrincipalInvalidTypeRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermKustoDatabasePrincipalInvalidTypeRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" is an invalid value as type`, truncateLongMessage(val)),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
