// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermHealthcareServiceInvalidCosmosdbThroughputRule checks the pattern is valid
type AzurermHealthcareServiceInvalidCosmosdbThroughputRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	min           int
}

// NewAzurermHealthcareServiceInvalidCosmosdbThroughputRule returns new rule with default attributes
func NewAzurermHealthcareServiceInvalidCosmosdbThroughputRule() *AzurermHealthcareServiceInvalidCosmosdbThroughputRule {
	return &AzurermHealthcareServiceInvalidCosmosdbThroughputRule{
		resourceType:  "azurerm_healthcare_service",
		attributeName: "cosmosdb_throughput",
		min:           400,
	}
}

// Name returns the rule name
func (r *AzurermHealthcareServiceInvalidCosmosdbThroughputRule) Name() string {
	return "azurerm_healthcare_service_invalid_cosmosdb_throughput"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermHealthcareServiceInvalidCosmosdbThroughputRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermHealthcareServiceInvalidCosmosdbThroughputRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermHealthcareServiceInvalidCosmosdbThroughputRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermHealthcareServiceInvalidCosmosdbThroughputRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}
		var val int
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			if val < r.min {
				runner.EmitIssue(
					r,
					"cosmosdb_throughput must be 400 or higher",
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
