// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule checks the pattern is valid
type AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	max           int
	min           int
}

// NewAzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule returns new rule with default attributes
func NewAzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule() *AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule {
	return &AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule{
		resourceType:  "azurerm_kubernetes_cluster_node_pool",
		attributeName: "os_disk_size_gb",
		max:           2048,
		min:           0,
	}
}

// Name returns the rule name
func (r *AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule) Name() string {
	return "azurerm_kubernetes_cluster_node_pool_invalid_os_disk_size_gb"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermKubernetesClusterNodePoolInvalidOSDiskSizeGbRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}
		var val int
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			if val > r.max {
				runner.EmitIssue(
					r,
					"os_disk_size_gb must be 2048 or less",
					attribute.Expr.Range(),
				)
			}
			if val < r.min {
				runner.EmitIssue(
					r,
					"os_disk_size_gb must be 0 or higher",
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
