// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermCdnEndpointInvalidQuerystringCachingBehaviourRule checks the pattern is valid
type AzurermCdnEndpointInvalidQuerystringCachingBehaviourRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermCdnEndpointInvalidQuerystringCachingBehaviourRule returns new rule with default attributes
func NewAzurermCdnEndpointInvalidQuerystringCachingBehaviourRule() *AzurermCdnEndpointInvalidQuerystringCachingBehaviourRule {
	return &AzurermCdnEndpointInvalidQuerystringCachingBehaviourRule{
		resourceType:  "azurerm_cdn_endpoint",
		attributeName: "querystring_caching_behaviour",
		enum: []string{
			"IgnoreQueryString",
			"BypassCaching",
			"UseQueryString",
			"NotSet",
		},
	}
}

// Name returns the rule name
func (r *AzurermCdnEndpointInvalidQuerystringCachingBehaviourRule) Name() string {
	return "azurerm_cdn_endpoint_invalid_querystring_caching_behaviour"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermCdnEndpointInvalidQuerystringCachingBehaviourRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermCdnEndpointInvalidQuerystringCachingBehaviourRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermCdnEndpointInvalidQuerystringCachingBehaviourRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermCdnEndpointInvalidQuerystringCachingBehaviourRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" is an invalid value as querystring_caching_behaviour`, truncateLongMessage(val)),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
