// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermKustoEventhubDataConnectionInvalidDataFormatRule checks the pattern is valid
type AzurermKustoEventhubDataConnectionInvalidDataFormatRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermKustoEventhubDataConnectionInvalidDataFormatRule returns new rule with default attributes
func NewAzurermKustoEventhubDataConnectionInvalidDataFormatRule() *AzurermKustoEventhubDataConnectionInvalidDataFormatRule {
	return &AzurermKustoEventhubDataConnectionInvalidDataFormatRule{
		resourceType:  "azurerm_kusto_eventhub_data_connection",
		attributeName: "data_format",
		enum: []string{
			"MULTIJSON",
			"JSON",
			"CSV",
			"TSV",
			"SCSV",
			"SOHSV",
			"PSV",
			"TXT",
			"RAW",
			"SINGLEJSON",
			"AVRO",
			"TSVE",
			"PARQUET",
			"ORC",
			"APACHEAVRO",
			"W3CLOGFILE",
		},
	}
}

// Name returns the rule name
func (r *AzurermKustoEventhubDataConnectionInvalidDataFormatRule) Name() string {
	return "azurerm_kusto_eventhub_data_connection_invalid_data_format"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermKustoEventhubDataConnectionInvalidDataFormatRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermKustoEventhubDataConnectionInvalidDataFormatRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermKustoEventhubDataConnectionInvalidDataFormatRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermKustoEventhubDataConnectionInvalidDataFormatRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as data_format`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
