// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermMssqlDatabaseInvalidLicenseTypeRule checks the pattern is valid
type AzurermMssqlDatabaseInvalidLicenseTypeRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermMssqlDatabaseInvalidLicenseTypeRule returns new rule with default attributes
func NewAzurermMssqlDatabaseInvalidLicenseTypeRule() *AzurermMssqlDatabaseInvalidLicenseTypeRule {
	return &AzurermMssqlDatabaseInvalidLicenseTypeRule{
		resourceType:  "azurerm_mssql_database",
		attributeName: "license_type",
		enum: []string{
			"LicenseIncluded",
			"BasePrice",
		},
	}
}

// Name returns the rule name
func (r *AzurermMssqlDatabaseInvalidLicenseTypeRule) Name() string {
	return "azurerm_mssql_database_invalid_license_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermMssqlDatabaseInvalidLicenseTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermMssqlDatabaseInvalidLicenseTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermMssqlDatabaseInvalidLicenseTypeRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermMssqlDatabaseInvalidLicenseTypeRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as license_type`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
