// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermVirtualNetworkGatewayInvalidVpnTypeRule checks the pattern is valid
type AzurermVirtualNetworkGatewayInvalidVpnTypeRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermVirtualNetworkGatewayInvalidVpnTypeRule returns new rule with default attributes
func NewAzurermVirtualNetworkGatewayInvalidVpnTypeRule() *AzurermVirtualNetworkGatewayInvalidVpnTypeRule {
	return &AzurermVirtualNetworkGatewayInvalidVpnTypeRule{
		resourceType:  "azurerm_virtual_network_gateway",
		attributeName: "vpn_type",
		enum: []string{
			"PolicyBased",
			"RouteBased",
		},
	}
}

// Name returns the rule name
func (r *AzurermVirtualNetworkGatewayInvalidVpnTypeRule) Name() string {
	return "azurerm_virtual_network_gateway_invalid_vpn_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermVirtualNetworkGatewayInvalidVpnTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermVirtualNetworkGatewayInvalidVpnTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermVirtualNetworkGatewayInvalidVpnTypeRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermVirtualNetworkGatewayInvalidVpnTypeRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" is an invalid value as vpn_type`, truncateLongMessage(val)),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
