// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"
	"regexp"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermContainerRegistryWebhookInvalidRegistryNameRule checks the pattern is valid
type AzurermContainerRegistryWebhookInvalidRegistryNameRule struct {
	resourceType  string
	attributeName string
	pattern       *regexp.Regexp
}

// NewAzurermContainerRegistryWebhookInvalidRegistryNameRule returns new rule with default attributes
func NewAzurermContainerRegistryWebhookInvalidRegistryNameRule() *AzurermContainerRegistryWebhookInvalidRegistryNameRule {
	return &AzurermContainerRegistryWebhookInvalidRegistryNameRule{
		resourceType:  "azurerm_container_registry_webhook",
		attributeName: "registry_name",
		pattern:       regexp.MustCompile(`^[a-zA-Z0-9]*$`),
	}
}

// Name returns the rule name
func (r *AzurermContainerRegistryWebhookInvalidRegistryNameRule) Name() string {
	return "azurerm_container_registry_webhook_invalid_registry_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermContainerRegistryWebhookInvalidRegistryNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermContainerRegistryWebhookInvalidRegistryNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermContainerRegistryWebhookInvalidRegistryNameRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermContainerRegistryWebhookInvalidRegistryNameRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if !r.pattern.MatchString(val) {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^[a-zA-Z0-9]*$`),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
