// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AzurermHealthcareServiceInvalidKindRule checks the pattern is valid
type AzurermHealthcareServiceInvalidKindRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermHealthcareServiceInvalidKindRule returns new rule with default attributes
func NewAzurermHealthcareServiceInvalidKindRule() *AzurermHealthcareServiceInvalidKindRule {
	return &AzurermHealthcareServiceInvalidKindRule{
		resourceType:  "azurerm_healthcare_service",
		attributeName: "kind",
		enum: []string{
			"fhir",
			"fhir-Stu3",
			"fhir-R4",
		},
	}
}

// Name returns the rule name
func (r *AzurermHealthcareServiceInvalidKindRule) Name() string {
	return "azurerm_healthcare_service_invalid_kind"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermHealthcareServiceInvalidKindRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermHealthcareServiceInvalidKindRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermHealthcareServiceInvalidKindRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AzurermHealthcareServiceInvalidKindRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as kind`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
