// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermEventhubNamespaceInvalidSkuRule checks the pattern is valid
type AzurermEventhubNamespaceInvalidSkuRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermEventhubNamespaceInvalidSkuRule returns new rule with default attributes
func NewAzurermEventhubNamespaceInvalidSkuRule() *AzurermEventhubNamespaceInvalidSkuRule {
	return &AzurermEventhubNamespaceInvalidSkuRule{
		resourceType:  "azurerm_eventhub_namespace",
		attributeName: "sku",
		enum: []string{
			"Basic",
			"Standard",
		},
	}
}

// Name returns the rule name
func (r *AzurermEventhubNamespaceInvalidSkuRule) Name() string {
	return "azurerm_eventhub_namespace_invalid_sku"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermEventhubNamespaceInvalidSkuRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermEventhubNamespaceInvalidSkuRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermEventhubNamespaceInvalidSkuRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermEventhubNamespaceInvalidSkuRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" is an invalid value as sku`, truncateLongMessage(val)),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
