// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AzurermManagedApplicationDefinitionInvalidLockLevelRule checks the pattern is valid
type AzurermManagedApplicationDefinitionInvalidLockLevelRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermManagedApplicationDefinitionInvalidLockLevelRule returns new rule with default attributes
func NewAzurermManagedApplicationDefinitionInvalidLockLevelRule() *AzurermManagedApplicationDefinitionInvalidLockLevelRule {
	return &AzurermManagedApplicationDefinitionInvalidLockLevelRule{
		resourceType:  "azurerm_managed_application_definition",
		attributeName: "lock_level",
		enum: []string{
			"CanNotDelete",
			"ReadOnly",
			"None",
		},
	}
}

// Name returns the rule name
func (r *AzurermManagedApplicationDefinitionInvalidLockLevelRule) Name() string {
	return "azurerm_managed_application_definition_invalid_lock_level"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermManagedApplicationDefinitionInvalidLockLevelRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermManagedApplicationDefinitionInvalidLockLevelRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermManagedApplicationDefinitionInvalidLockLevelRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AzurermManagedApplicationDefinitionInvalidLockLevelRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as lock_level`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
