// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermSQLDatabaseInvalidEditionRule checks the pattern is valid
type AzurermSQLDatabaseInvalidEditionRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermSQLDatabaseInvalidEditionRule returns new rule with default attributes
func NewAzurermSQLDatabaseInvalidEditionRule() *AzurermSQLDatabaseInvalidEditionRule {
	return &AzurermSQLDatabaseInvalidEditionRule{
		resourceType:  "azurerm_sql_database",
		attributeName: "edition",
		enum: []string{
			"Web",
			"Business",
			"Basic",
			"Standard",
			"Premium",
			"PremiumRS",
			"Free",
			"Stretch",
			"DataWarehouse",
			"System",
			"System2",
			"GeneralPurpose",
			"BusinessCritical",
			"Hyperscale",
		},
	}
}

// Name returns the rule name
func (r *AzurermSQLDatabaseInvalidEditionRule) Name() string {
	return "azurerm_sql_database_invalid_edition"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermSQLDatabaseInvalidEditionRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermSQLDatabaseInvalidEditionRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermSQLDatabaseInvalidEditionRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermSQLDatabaseInvalidEditionRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" is an invalid value as edition`, truncateLongMessage(val)),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
