// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermMaintenanceConfigurationInvalidScopeRule checks the pattern is valid
type AzurermMaintenanceConfigurationInvalidScopeRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermMaintenanceConfigurationInvalidScopeRule returns new rule with default attributes
func NewAzurermMaintenanceConfigurationInvalidScopeRule() *AzurermMaintenanceConfigurationInvalidScopeRule {
	return &AzurermMaintenanceConfigurationInvalidScopeRule{
		resourceType:  "azurerm_maintenance_configuration",
		attributeName: "scope",
		enum: []string{
			"All",
			"Host",
			"Resource",
			"InResource",
		},
	}
}

// Name returns the rule name
func (r *AzurermMaintenanceConfigurationInvalidScopeRule) Name() string {
	return "azurerm_maintenance_configuration_invalid_scope"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermMaintenanceConfigurationInvalidScopeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermMaintenanceConfigurationInvalidScopeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermMaintenanceConfigurationInvalidScopeRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermMaintenanceConfigurationInvalidScopeRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as scope`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
