// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermKustoEventhubDataConnectionInvalidDataFormatRule checks the pattern is valid
type AzurermKustoEventhubDataConnectionInvalidDataFormatRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermKustoEventhubDataConnectionInvalidDataFormatRule returns new rule with default attributes
func NewAzurermKustoEventhubDataConnectionInvalidDataFormatRule() *AzurermKustoEventhubDataConnectionInvalidDataFormatRule {
	return &AzurermKustoEventhubDataConnectionInvalidDataFormatRule{
		resourceType:  "azurerm_kusto_eventhub_data_connection",
		attributeName: "data_format",
		enum: []string{
			"MULTIJSON",
			"JSON",
			"CSV",
			"TSV",
			"SCSV",
			"SOHSV",
			"PSV",
			"TXT",
			"RAW",
			"SINGLEJSON",
			"AVRO",
			"TSVE",
			"PARQUET",
			"ORC",
		},
	}
}

// Name returns the rule name
func (r *AzurermKustoEventhubDataConnectionInvalidDataFormatRule) Name() string {
	return "azurerm_kusto_eventhub_data_connection_invalid_data_format"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermKustoEventhubDataConnectionInvalidDataFormatRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermKustoEventhubDataConnectionInvalidDataFormatRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermKustoEventhubDataConnectionInvalidDataFormatRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermKustoEventhubDataConnectionInvalidDataFormatRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as data_format`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
