// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermDataFactoryIntegrationRuntimeManagedInvalidNumberOfNodesRule checks the pattern is valid
type AzurermDataFactoryIntegrationRuntimeManagedInvalidNumberOfNodesRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	min           int
}

// NewAzurermDataFactoryIntegrationRuntimeManagedInvalidNumberOfNodesRule returns new rule with default attributes
func NewAzurermDataFactoryIntegrationRuntimeManagedInvalidNumberOfNodesRule() *AzurermDataFactoryIntegrationRuntimeManagedInvalidNumberOfNodesRule {
	return &AzurermDataFactoryIntegrationRuntimeManagedInvalidNumberOfNodesRule{
		resourceType:  "azurerm_data_factory_integration_runtime_managed",
		attributeName: "number_of_nodes",
		min:           1,
	}
}

// Name returns the rule name
func (r *AzurermDataFactoryIntegrationRuntimeManagedInvalidNumberOfNodesRule) Name() string {
	return "azurerm_data_factory_integration_runtime_managed_invalid_number_of_nodes"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermDataFactoryIntegrationRuntimeManagedInvalidNumberOfNodesRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermDataFactoryIntegrationRuntimeManagedInvalidNumberOfNodesRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermDataFactoryIntegrationRuntimeManagedInvalidNumberOfNodesRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermDataFactoryIntegrationRuntimeManagedInvalidNumberOfNodesRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}
		var val int
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			if val < r.min {
				runner.EmitIssue(
					r,
					"number_of_nodes must be 1 or higher",
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
