// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AzurermExpressRouteCircuitPeeringInvalidPeeringTypeRule checks the pattern is valid
type AzurermExpressRouteCircuitPeeringInvalidPeeringTypeRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermExpressRouteCircuitPeeringInvalidPeeringTypeRule returns new rule with default attributes
func NewAzurermExpressRouteCircuitPeeringInvalidPeeringTypeRule() *AzurermExpressRouteCircuitPeeringInvalidPeeringTypeRule {
	return &AzurermExpressRouteCircuitPeeringInvalidPeeringTypeRule{
		resourceType:  "azurerm_express_route_circuit_peering",
		attributeName: "peering_type",
		enum: []string{
			"AzurePublicPeering",
			"AzurePrivatePeering",
			"MicrosoftPeering",
		},
	}
}

// Name returns the rule name
func (r *AzurermExpressRouteCircuitPeeringInvalidPeeringTypeRule) Name() string {
	return "azurerm_express_route_circuit_peering_invalid_peering_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermExpressRouteCircuitPeeringInvalidPeeringTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermExpressRouteCircuitPeeringInvalidPeeringTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermExpressRouteCircuitPeeringInvalidPeeringTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AzurermExpressRouteCircuitPeeringInvalidPeeringTypeRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as peering_type`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
