// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermMonitorScheduledQueryRulesAlertInvalidSeverityRule checks the pattern is valid
type AzurermMonitorScheduledQueryRulesAlertInvalidSeverityRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermMonitorScheduledQueryRulesAlertInvalidSeverityRule returns new rule with default attributes
func NewAzurermMonitorScheduledQueryRulesAlertInvalidSeverityRule() *AzurermMonitorScheduledQueryRulesAlertInvalidSeverityRule {
	return &AzurermMonitorScheduledQueryRulesAlertInvalidSeverityRule{
		resourceType:  "azurerm_monitor_scheduled_query_rules_alert",
		attributeName: "severity",
		enum: []string{
			"0",
			"1",
			"2",
			"3",
			"4",
		},
	}
}

// Name returns the rule name
func (r *AzurermMonitorScheduledQueryRulesAlertInvalidSeverityRule) Name() string {
	return "azurerm_monitor_scheduled_query_rules_alert_invalid_severity"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermMonitorScheduledQueryRulesAlertInvalidSeverityRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermMonitorScheduledQueryRulesAlertInvalidSeverityRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermMonitorScheduledQueryRulesAlertInvalidSeverityRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermMonitorScheduledQueryRulesAlertInvalidSeverityRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as severity`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
