// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermDatabaseMigrationProjectInvalidSourcePlatformRule checks the pattern is valid
type AzurermDatabaseMigrationProjectInvalidSourcePlatformRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermDatabaseMigrationProjectInvalidSourcePlatformRule returns new rule with default attributes
func NewAzurermDatabaseMigrationProjectInvalidSourcePlatformRule() *AzurermDatabaseMigrationProjectInvalidSourcePlatformRule {
	return &AzurermDatabaseMigrationProjectInvalidSourcePlatformRule{
		resourceType:  "azurerm_database_migration_project",
		attributeName: "source_platform",
		enum: []string{
			"SQL",
			"Unknown",
		},
	}
}

// Name returns the rule name
func (r *AzurermDatabaseMigrationProjectInvalidSourcePlatformRule) Name() string {
	return "azurerm_database_migration_project_invalid_source_platform"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermDatabaseMigrationProjectInvalidSourcePlatformRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermDatabaseMigrationProjectInvalidSourcePlatformRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermDatabaseMigrationProjectInvalidSourcePlatformRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermDatabaseMigrationProjectInvalidSourcePlatformRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as source_platform`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
