// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AzurermLogAnalyticsWorkspaceInvalidSkuRule checks the pattern is valid
type AzurermLogAnalyticsWorkspaceInvalidSkuRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermLogAnalyticsWorkspaceInvalidSkuRule returns new rule with default attributes
func NewAzurermLogAnalyticsWorkspaceInvalidSkuRule() *AzurermLogAnalyticsWorkspaceInvalidSkuRule {
	return &AzurermLogAnalyticsWorkspaceInvalidSkuRule{
		resourceType:  "azurerm_log_analytics_workspace",
		attributeName: "sku",
		enum: []string{
			"Free",
			"Standard",
			"Premium",
			"PerNode",
			"PerGB2018",
			"Standalone",
			"CapacityReservation",
		},
	}
}

// Name returns the rule name
func (r *AzurermLogAnalyticsWorkspaceInvalidSkuRule) Name() string {
	return "azurerm_log_analytics_workspace_invalid_sku"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermLogAnalyticsWorkspaceInvalidSkuRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermLogAnalyticsWorkspaceInvalidSkuRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermLogAnalyticsWorkspaceInvalidSkuRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AzurermLogAnalyticsWorkspaceInvalidSkuRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as sku`, truncateLongMessage(val)),
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
