// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermHdinsightInteractiveQueryClusterInvalidTierRule checks the pattern is valid
type AzurermHdinsightInteractiveQueryClusterInvalidTierRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermHdinsightInteractiveQueryClusterInvalidTierRule returns new rule with default attributes
func NewAzurermHdinsightInteractiveQueryClusterInvalidTierRule() *AzurermHdinsightInteractiveQueryClusterInvalidTierRule {
	return &AzurermHdinsightInteractiveQueryClusterInvalidTierRule{
		resourceType:  "azurerm_hdinsight_interactive_query_cluster",
		attributeName: "tier",
		enum: []string{
			"Standard",
			"Premium",
		},
	}
}

// Name returns the rule name
func (r *AzurermHdinsightInteractiveQueryClusterInvalidTierRule) Name() string {
	return "azurerm_hdinsight_interactive_query_cluster_invalid_tier"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermHdinsightInteractiveQueryClusterInvalidTierRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermHdinsightInteractiveQueryClusterInvalidTierRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermHdinsightInteractiveQueryClusterInvalidTierRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermHdinsightInteractiveQueryClusterInvalidTierRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" is an invalid value as tier`, truncateLongMessage(val)),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
