// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AzurermExpressRouteCircuitPeeringInvalidPeerAsnRule checks the pattern is valid
type AzurermExpressRouteCircuitPeeringInvalidPeerAsnRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
}

// NewAzurermExpressRouteCircuitPeeringInvalidPeerAsnRule returns new rule with default attributes
func NewAzurermExpressRouteCircuitPeeringInvalidPeerAsnRule() *AzurermExpressRouteCircuitPeeringInvalidPeerAsnRule {
	return &AzurermExpressRouteCircuitPeeringInvalidPeerAsnRule{
		resourceType:  "azurerm_express_route_circuit_peering",
		attributeName: "peer_asn",
		max:           4294967295,
		min:           1,
	}
}

// Name returns the rule name
func (r *AzurermExpressRouteCircuitPeeringInvalidPeerAsnRule) Name() string {
	return "azurerm_express_route_circuit_peering_invalid_peer_asn"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermExpressRouteCircuitPeeringInvalidPeerAsnRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermExpressRouteCircuitPeeringInvalidPeerAsnRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermExpressRouteCircuitPeeringInvalidPeerAsnRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AzurermExpressRouteCircuitPeeringInvalidPeerAsnRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val int
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if val > r.max {
				runner.EmitIssue(
					r,
					"peer_asn must be 4294967295 or less",
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			if val < r.min {
				runner.EmitIssue(
					r,
					"peer_asn must be 1 or higher",
					attribute.Expr.Range(),
					tflint.Metadata{Expr: attribute.Expr},
				)
			}
			return nil
		})
	})
}
