// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermLbOutboundRuleInvalidProtocolRule checks the pattern is valid
type AzurermLbOutboundRuleInvalidProtocolRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermLbOutboundRuleInvalidProtocolRule returns new rule with default attributes
func NewAzurermLbOutboundRuleInvalidProtocolRule() *AzurermLbOutboundRuleInvalidProtocolRule {
	return &AzurermLbOutboundRuleInvalidProtocolRule{
		resourceType:  "azurerm_lb_outbound_rule",
		attributeName: "protocol",
		enum: []string{
			"Tcp",
			"Udp",
			"All",
		},
	}
}

// Name returns the rule name
func (r *AzurermLbOutboundRuleInvalidProtocolRule) Name() string {
	return "azurerm_lb_outbound_rule_invalid_protocol"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermLbOutboundRuleInvalidProtocolRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermLbOutboundRuleInvalidProtocolRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermLbOutboundRuleInvalidProtocolRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermLbOutboundRuleInvalidProtocolRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" is an invalid value as protocol`, truncateLongMessage(val)),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
