// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermStreamAnalyticsJobInvalidCompatibilityLevelRule checks the pattern is valid
type AzurermStreamAnalyticsJobInvalidCompatibilityLevelRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermStreamAnalyticsJobInvalidCompatibilityLevelRule returns new rule with default attributes
func NewAzurermStreamAnalyticsJobInvalidCompatibilityLevelRule() *AzurermStreamAnalyticsJobInvalidCompatibilityLevelRule {
	return &AzurermStreamAnalyticsJobInvalidCompatibilityLevelRule{
		resourceType:  "azurerm_stream_analytics_job",
		attributeName: "compatibility_level",
		enum: []string{
			"1.0",
		},
	}
}

// Name returns the rule name
func (r *AzurermStreamAnalyticsJobInvalidCompatibilityLevelRule) Name() string {
	return "azurerm_stream_analytics_job_invalid_compatibility_level"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermStreamAnalyticsJobInvalidCompatibilityLevelRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermStreamAnalyticsJobInvalidCompatibilityLevelRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermStreamAnalyticsJobInvalidCompatibilityLevelRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermStreamAnalyticsJobInvalidCompatibilityLevelRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" is an invalid value as compatibility_level`, truncateLongMessage(val)),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
