// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermSQLElasticpoolInvalidEditionRule checks the pattern is valid
type AzurermSQLElasticpoolInvalidEditionRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermSQLElasticpoolInvalidEditionRule returns new rule with default attributes
func NewAzurermSQLElasticpoolInvalidEditionRule() *AzurermSQLElasticpoolInvalidEditionRule {
	return &AzurermSQLElasticpoolInvalidEditionRule{
		resourceType:  "azurerm_sql_elasticpool",
		attributeName: "edition",
		enum: []string{
			"Basic",
			"Standard",
			"Premium",
			"GeneralPurpose",
			"BusinessCritical",
		},
	}
}

// Name returns the rule name
func (r *AzurermSQLElasticpoolInvalidEditionRule) Name() string {
	return "azurerm_sql_elasticpool_invalid_edition"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermSQLElasticpoolInvalidEditionRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermSQLElasticpoolInvalidEditionRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermSQLElasticpoolInvalidEditionRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermSQLElasticpoolInvalidEditionRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" is an invalid value as edition`, truncateLongMessage(val)),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
