// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermManagedDiskInvalidStorageAccountTypeRule checks the pattern is valid
type AzurermManagedDiskInvalidStorageAccountTypeRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermManagedDiskInvalidStorageAccountTypeRule returns new rule with default attributes
func NewAzurermManagedDiskInvalidStorageAccountTypeRule() *AzurermManagedDiskInvalidStorageAccountTypeRule {
	return &AzurermManagedDiskInvalidStorageAccountTypeRule{
		resourceType:  "azurerm_managed_disk",
		attributeName: "storage_account_type",
		enum: []string{
			"Standard_LRS",
			"Premium_LRS",
			"StandardSSD_LRS",
			"UltraSSD_LRS",
		},
	}
}

// Name returns the rule name
func (r *AzurermManagedDiskInvalidStorageAccountTypeRule) Name() string {
	return "azurerm_managed_disk_invalid_storage_account_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermManagedDiskInvalidStorageAccountTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermManagedDiskInvalidStorageAccountTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermManagedDiskInvalidStorageAccountTypeRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermManagedDiskInvalidStorageAccountTypeRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" is an invalid value as storage_account_type`, truncateLongMessage(val)),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
