// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermTrafficManagerProfileInvalidTrafficRoutingMethodRule checks the pattern is valid
type AzurermTrafficManagerProfileInvalidTrafficRoutingMethodRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermTrafficManagerProfileInvalidTrafficRoutingMethodRule returns new rule with default attributes
func NewAzurermTrafficManagerProfileInvalidTrafficRoutingMethodRule() *AzurermTrafficManagerProfileInvalidTrafficRoutingMethodRule {
	return &AzurermTrafficManagerProfileInvalidTrafficRoutingMethodRule{
		resourceType:  "azurerm_traffic_manager_profile",
		attributeName: "traffic_routing_method",
		enum: []string{
			"Performance",
			"Priority",
			"Weighted",
			"Geographic",
			"MultiValue",
			"Subnet",
		},
	}
}

// Name returns the rule name
func (r *AzurermTrafficManagerProfileInvalidTrafficRoutingMethodRule) Name() string {
	return "azurerm_traffic_manager_profile_invalid_traffic_routing_method"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermTrafficManagerProfileInvalidTrafficRoutingMethodRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermTrafficManagerProfileInvalidTrafficRoutingMethodRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermTrafficManagerProfileInvalidTrafficRoutingMethodRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermTrafficManagerProfileInvalidTrafficRoutingMethodRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}
		err := runner.EvaluateExpr(attribute.Expr, func (val string) error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as traffic_routing_method`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
