// This file generated by `tools/apispec-rule-gen/main.go`. DO NOT EDIT

package apispec

import (
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-azurerm/project"
)

// AzurermHealthcareServiceInvalidKindRule checks the pattern is valid
type AzurermHealthcareServiceInvalidKindRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAzurermHealthcareServiceInvalidKindRule returns new rule with default attributes
func NewAzurermHealthcareServiceInvalidKindRule() *AzurermHealthcareServiceInvalidKindRule {
	return &AzurermHealthcareServiceInvalidKindRule{
		resourceType:  "azurerm_healthcare_service",
		attributeName: "kind",
		enum: []string{
			"fhir",
			"fhir-Stu3",
			"fhir-R4",
		},
	}
}

// Name returns the rule name
func (r *AzurermHealthcareServiceInvalidKindRule) Name() string {
	return "azurerm_healthcare_service_invalid_kind"
}

// Enabled returns whether the rule is enabled by default
func (r *AzurermHealthcareServiceInvalidKindRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AzurermHealthcareServiceInvalidKindRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AzurermHealthcareServiceInvalidKindRule) Link() string {
	return project.ReferenceLink(r.Name())
}

// Check checks the pattern is valid
func (r *AzurermHealthcareServiceInvalidKindRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as kind`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
