name: maintenance

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch: # Enables on-demand/manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      - run: |
          cd tools/apispec-rule-gen/schema
          terraform init -upgrade
          terraform providers schema -json > schema.json
          cd ../..
          git submodule update --remote
          go run ./api-version-bumper
          go run ./apispec-rule-gen
          cd ../rules/tags/generator
          go run -tags generators .
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: |
            autogenerated maintenance
          title: autogenerated maintenance
          delete-branch: true
          body: |
            If tests are stuck on https://github.com/peter-evans/create-pull-request/issues/48:
            ["Manually close pull requests and immediately reopen them. This will enable `on: pull_request` workflows to run and be added as checks."](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs)
